@startuml
class NullableBoolToBoolConverter {
    + Convert(value:object?, targetType:Type, parameter:object?, culture:CultureInfo) : object
    + ConvertBack(value:object?, targetType:Type, parameter:object?, culture:CultureInfo) : object?
}
IValueConverter <|-- NullableBoolToBoolConverter
@enduml
