@startuml
class RelayCommand {
    - <<readonly>> _canExecute : Func<object, bool>?
    + RelayCommand(execute:Action<object>, canExecute:Func<object, bool>?)
    + CanExecute(parameter:object?) : bool
    + Execute(parameter:object?) : void
    + RaiseCanExecuteChanged() : void
}
class "Action`1"<T> {
}
ICommand <|-- RelayCommand
RelayCommand --> "_execute<object>" "Action`1"
@enduml
