@startuml
!include .\\Converter\CollectionToStringConverter.puml
!include .\\Converter\DateOnlyToDateTimeConverter.puml
!include .\\Converter\NullableBoolToBoolConverter.puml
!include .\\Database\DataManager.puml
!include .\\Database\FiscalFlowDatabaseContext.puml
!include .\\Helpers\FormField.puml
!include .\\Helpers\Hasher.puml
!include .\\Model\Base.puml
!include .\\Model\Bill.puml
!include .\\Model\BlacklistedToken.puml
!include .\\Model\Credit.puml
!include .\\Model\Currency.puml
!include .\\Model\DailyCategoryExpense.puml
!include .\\Model\DailyReport.puml
!include .\\Model\Debt.puml
!include .\\Model\DeviceToken.puml
!include .\\Model\MonthlyExpense.puml
!include .\\Model\Notification.puml
!include .\\Model\NotificationProfile.puml
!include .\\Model\OutstandingToken.puml
!include .\\Model\Profile.puml
!include .\\Model\Transaction.puml
!include .\\Model\TransactionCategory.puml
!include .\\Model\User.puml
!include .\\ViewModel\AdminPageViewModel.puml
!include .\\ViewModel\BaseViewModel.puml
!include .\\ViewModel\MainWindowViewModel.puml
!include .\\ViewModel\ViewModelBase.puml
!include .\\Database\Repositories\BaseRepository.puml
!include .\\Database\Repositories\IRepository.puml
!include .\\Model\Attributes\BlankAttribute.puml
!include .\\Model\Attributes\CollectionAttribute.puml
!include .\\Model\Attributes\DataGridIgnoreAttribute.puml
!include .\\Model\Attributes\DisplayMemberPathAttribute.puml
!include .\\Model\Attributes\FormIgnoreAttribute.puml
!include .\\Model\Attributes\NullableAttribute.puml
!include .\\Model\Attributes\OrderAttribute.puml
!include .\\Model\Attributes\PlaceholderAttribute.puml
!include .\\Model\Attributes\PreHashed.puml
!include .\\Model\Attributes\TooltipAttribute.puml
!include .\\View\Controls\EntityManagementView.xaml.puml
!include .\\View\Pages\AdminPage.xaml.puml
!include .\\View\Windows\AdminWindow.xaml.puml
!include .\\ViewModel\Commands\RelayCommand.puml
!include .\\Database\Repositories\Authentication\DeviceTokenRepository.puml
!include .\\Database\Repositories\Authentication\ProfileRepository.puml
!include .\\Database\Repositories\Authentication\UserRepository.puml
!include .\\Database\Repositories\Finances\BillRepository.puml
!include .\\Database\Repositories\Finances\CreditRepository.puml
!include .\\Database\Repositories\Finances\CurrencyRepository.puml
!include .\\Database\Repositories\Finances\DailyCategoryExpenseRepository.puml
!include .\\Database\Repositories\Finances\DailyReportRepository.puml
!include .\\Database\Repositories\Finances\DebtRepository.puml
!include .\\Database\Repositories\Finances\MonthlyExpenseRepository.puml
!include .\\Database\Repositories\Finances\TransactionCategoryRepository.puml
!include .\\Database\Repositories\Finances\TransactionRepository.puml
!include .\\Database\Repositories\Reminders\NotificationProfileRepository.puml
!include .\\Database\Repositories\Reminders\NotificationRepository.puml
!include .\\Database\Repositories\Token\BlacklistedTokenRepository.puml
!include .\\Database\Repositories\Token\OutstandingTokenRepository.puml
!include .\\obj\Debug\net8.0-windows\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\obj\Debug\net8.0-windows\App.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_0frdlpbu_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_0frdlpbu_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_0kwj2sgo_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_0kwj2sgo_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_0pn4eihn_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_0pn4eihn_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_0xhudehy_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_0xhudehy_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_1e2ykzna_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_1e2ykzna_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_1idybueu_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_1idybueu_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_1qrtmkvi_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_1qrtmkvi_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_1sac1q1j_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_1sac1q1j_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_2gyibegg_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_2gyibegg_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_2kcxst3x_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_2kcxst3x_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_2wvckivj_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_2wvckivj_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_3kahswtz_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_3kahswtz_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_3olpm30s_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_3olpm30s_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_3v51125j_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_3v51125j_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_43k0nu1e_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_43k0nu1e_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_45zb4pmq_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_45zb4pmq_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_4qyucbex_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_4qyucbex_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_5cxdsgg2_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_5cxdsgg2_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_5qef0oyy_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_5qef0oyy_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_5yws5cv1_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_5yws5cv1_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_a0tnzavd_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_a0tnzavd_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_a24cqczx_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_a24cqczx_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_anbymmq2_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_anbymmq2_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_artmwthl_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_artmwthl_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_bosfgsfk_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_bosfgsfk_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_bv3stc0d_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_bv3stc0d_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_c0sx0yfm_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_c0sx0yfm_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_c1qgbesy_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_c1qgbesy_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_cjv52zdw_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_cjv52zdw_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_cnyxvqhc_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_cnyxvqhc_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_ctia3rwz_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_ctia3rwz_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_cvcw1jid_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_cvcw1jid_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_d1mt2esy_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_d1mt2esy_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_dcfw4wsu_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_dcfw4wsu_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_dmgjrnog_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_dmgjrnog_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_dryqhc22_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_dryqhc22_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_dtc1ynxy_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_dtc1ynxy_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_duljvkum_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_duljvkum_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_eex1qqti_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_eex1qqti_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_eikjmfxv_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_eikjmfxv_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_ekmp5skq_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_ekmp5skq_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_eo2oqf1c_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_eo2oqf1c_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_eqykqfeg_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_eqykqfeg_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_etlf4zwg_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_etlf4zwg_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_ewhfk4cz_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_ewhfk4cz_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_f3aydctn_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_f3aydctn_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_f4xw5g4w_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_f4xw5g4w_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_fakwitdx_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_fakwitdx_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_fjtxi5yo_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_fjtxi5yo_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_fsg22245_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_fsg22245_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_g0pusnyj_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_g0pusnyj_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_g4ztfiao_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_g4ztfiao_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_g5g30mer_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_g5g30mer_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_gcpz5ueo_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_gcpz5ueo_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_gicuv2dp_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_gicuv2dp_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_h2oo41vo_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_h2oo41vo_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_halk3w53_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_halk3w53_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_hnvyft4t_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_hnvyft4t_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_hpsbxtoe_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_hpsbxtoe_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_hq33upw5_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_hq33upw5_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_i1ggis00_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_i1ggis00_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_ifegy4rv_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_ifegy4rv_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_jfswcfe0_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_jfswcfe0_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_jjibftyp_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_jjibftyp_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_jlghowy1_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_jlghowy1_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_jlsizk5v_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_jlsizk5v_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_jy34mqvh_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_jy34mqvh_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_k3rkx31n_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_k3rkx31n_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_kao2xgul_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_kao2xgul_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_knue0t0y_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_knue0t0y_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_knwwqnfs_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_knwwqnfs_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_ksnbdgug_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_ksnbdgug_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_lhfrq420_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_lhfrq420_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_lmscu0dy_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_lmscu0dy_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_memmvkpa_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_memmvkpa_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_mlgxzpdh_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_mlgxzpdh_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_mmdrwyxt_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_mmdrwyxt_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_mnbu3exg_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_mnbu3exg_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_nc5ytlnx_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_nc5ytlnx_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_nyhb41fz_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_nyhb41fz_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_nzskm50p_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_nzskm50p_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_oh42cw24_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_oh42cw24_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_oqv20zel_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_oqv20zel_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_pbidtrv2_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_pbidtrv2_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_pe0ovu4x_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_pe0ovu4x_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_phi0szwe_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_phi0szwe_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_phikeuh1_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_phikeuh1_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_pkta3zjx_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_pkta3zjx_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_q2in20ec_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_q2in20ec_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_q2ugerzd_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_q2ugerzd_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_qiwjzd1t_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_qiwjzd1t_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_qvtdh4l3_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_qvtdh4l3_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_rkuiss31_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_rkuiss31_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_s3e4bodv_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_s3e4bodv_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_sbqepmhu_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_sbqepmhu_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_szn5utjc_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_szn5utjc_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_tda5rjll_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_tda5rjll_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_tdddsidl_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_tdddsidl_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_tobnotta_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_tobnotta_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_tsnsmlp4_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_tsnsmlp4_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_ufna3yxx_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_ufna3yxx_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_umpsf30f_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_umpsf30f_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_un4n5tah_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_un4n5tah_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_up4hrapf_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_up4hrapf_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_upci1zcf_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_upci1zcf_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_wcchnmc1_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_wcchnmc1_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_wswraegr_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_wswraegr_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_wtovpnxi_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_wtovpnxi_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_ww4vjkbg_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_ww4vjkbg_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_xgtlvs4w_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_xgtlvs4w_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_xpw144lv_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_xpw144lv_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_xutytosh_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_xutytosh_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_y0xxrb15_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_y0xxrb15_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_y2eb1kxt_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_y2eb1kxt_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_yhee0gpx_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_yhee0gpx_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_z2wzbeiv_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_z2wzbeiv_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_zgqqn4kv_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_zgqqn4kv_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_znplbh3i_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_znplbh3i_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_zqxr5xmg_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\FiscalFlowAdmin_zqxr5xmg_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\GeneratedInternalTypeHelper.g.puml
!include .\\obj\Debug\net8.0-windows\MainWindow.g.puml
!include .\\obj\Debug\net8.0-windows\View\Controls\EntityManagementView.g.puml
!include .\\obj\Debug\net8.0-windows\View\Pages\AdminPage.g.puml
!include .\\obj\Debug\net8.0-windows\View\Windows\AdminWindow.g.puml
@enduml
